version: '3.3'
services:
  auth-db:
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    tty: true
    ports:
      - '33061:3306'
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_ROOT_PASSWORD: md4436
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - './authdb:/var/lib/mysql/'
    networks:
      - bridge
    deploy:
      placement:
        constraints: [node.role == manager]

  auth-backend:
    image: localhost:5000/auth-backend:latest
    tty: true
    restart: always
    working_dir: /app
    networks:
      - bridge
    depends_on:
      - auth-db
    ports:
      - '8000:8000'
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=AUTH]
      placement:
        constraints: [node.role == worker]

  doctor-db:
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    tty: true
    ports:
      - '33062:3306'
    environment:
      MYSQL_DATABASE: doctordb
      MYSQL_ROOT_PASSWORD: md4436
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - './doctordb:/var/lib/mysql/'
    networks:
      - bridge
    deploy:
      placement:
        constraints: [node.role == manager]

  doctor-backend:
    image: localhost:5000/doctor-backend:latest
    tty: true
    restart: always
    working_dir: /app
    networks:
      - bridge
    depends_on:
      - doctor-db
    ports:
      - '8001:8000'
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=DOCTOR]
      placement:
        constraints: [node.role == worker]

  user-db:
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    tty: true
    ports:
      - '33063:3306'
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: md4436
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - './userdb:/var/lib/mysql/'
    networks:
      - bridge
    deploy:
      placement:
        constraints: [node.role == manager]


  user-backend:
    image: localhost:5000/user-backend:latest
    tty: true
    restart: always
    working_dir: /app
    networks:
      - bridge
    depends_on:
      - user-db
    ports:
      - '8002:8000'
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=USER]
      placement:
        constraints: [node.role == worker]


  user-panel:
    image: localhost:5000/user-panel:latest
    tty: true
    restart: always
    working_dir: /app
    ports:
      - '4000:4000'
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=FRONT]
      placement:
        constraints: [node.role == worker]


networks:
  bridge:
    external:
      name: bridge
